### ISSUE TITLE
Have the Microsoft.Experimental.IdentityModel.Clients NuGet packages been removed?

### ISSUE THREAD

**Issue by ben-rose** [AzureADQuickStarts/B2C-NativeClient-DotNet#3]
I've downloaded this example with the hope of using the library to connect to an azure b2c instance however NuGet updator / NuGet package manager can't seem to find the Experimental IdentityModel libraries. Could you advise whether these still exist, or have moved / renamed? Many thanks. Ben.

**Comment by phatcher** [comment]
@ben-rose The package is experimental so you need to allow pre-release packages to be found e.g.

install-package Microsoft.Experimental.IdentityModel.Clients  -includePrerelease
