### ISSUE TITLE
SignUp fails no matter wich provider I choose

### ISSUE THREAD

**Issue by ncarandini** [AzureADQuickStarts/B2C-NativeClient-DotNet#6]
I did succeed with other Quickstart Guides:
- Build a ​.NET Web App
- Sign up and sign in on an ASP​.NET web app
- Build a .NET web API

But with this one nothing is working.
While signing up the user, the registration to my AAD B2C tenant succeed (I can find the new user after the failed sign up operation) but the `pca.AcquireTokenAsync` operation then fails throwing this exception:
"The browser based authentication dialog failed to complete. Reason: The protocol is not known and no pluggable protocols have been entered that match."

I've tried with MSA, Google and Facebook, with the same result (user successfully added to the AAD B2C tenant users list, but operation failed).

Any help?

**Comment by ncarandini** [comment]
Ok, just found it was already asked on a closed issue. Maybe a small note in the article would have saved me some time... :-)

**Comment by derisen** [comment]
Closing as this repo is being archived.
